### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by KorrumzPL** [SkyndalexProjects/Skyndalex#6]
# Earning methods

- [x]  /work
- [x] /crime
- [x] /slut
- [ ] /role-collect

# Games

- [ ] /roulette
- [ ] /slot-machine

# Fun
- [ ] /rob

# Config
## Sentences
- [x] /text set Work
- [x] /text set Crime
- [x] /text set Slut
- [x] /text remove Work
- [x] /text remove Crime
- [x] /text remove Slut
- [x] /text update Work
- [x] /text update Crime
- [x] /text update Slut
### Cooldowns
- [x] Work
- [x] Crime
- [x] Slut
- [ ] role-collect
# Management
## User
- [x]  /add-money
- [x]  /take-money
## Server
- [ ] /migration

# Utils
- [x] /bal

**Comment by banocean** [comment]
Name `take-money` suggests that someone who does it receives taken amount. Not sure what is it for.
